### ISSUE TITLE
Doesn't launch from the application menu unless I edit the .desktop file

### ISSUE THREAD

**Issue by pizzadude** [flathub/com.system76.Popsicle#1]
Doesn't launch from the application menu unless I edit the .desktop file.

In Fedora 32 KDE, I need to remove the:

 --command=/usr/local/bin/popsicle-gtk

from this: 

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/usr/local/bin/popsicle-gtk --file-forwarding com.system76.Popsicle @@u %U @@

in order to get the flatpak to run from the menu.

This is the same problem as https://github.com/flathub/io.github.hakuneko.HakuNeko/issues/1

**Comment by ids1024** [comment]
Good catch! This should be fixed in https://github.com/flathub/com.system76.Popsicle/commit/0f64e942d188a54db110474bc8fe830384f2fd80.
