### ISSUE TITLE
Update platform/runtime to Freedesktop 22.08

### ISSUE THREAD

**Issue by x80486** [flathub/com.system76.Popsicle#4]

**Comment by mixalis1987** [comment]
It doesnt look like this flatpak is being work on. The programs github has version 1.3.1 and this flatpak is 1.3.0. Might be worth just removing the flatpak and using the appimage they have on github.

**Comment by ids1024** [comment]
Updated in https://github.com/flathub/com.system76.Popsicle/pull/8.
